<?php
/**
 * Attributes File.
 *
 * @since x.x.x
 *
 * @package uagb
 */

return array(
	'block_id'                => '',
	'layout'                  => 'input-button',
	'placeholder'             => 'Type & Hit Enter',
	'inputSize'               => 100,
	'textColor'               => '',
	'inputBgColor'            => '#ECEEEF',
	'boxShadowColor'          => '',
	'boxShadowHOffset'        => 0,
	'boxShadowVOffset'        => 0,
	'boxShadowBlur'           => '',
	'boxShadowSpread'         => '',
	'boxShadowPosition'       => 'outset',
	'borderStyle'             => 'none',
	'borderWidth'             => '',
	'borderRadius'            => 3,
	'borderColor'             => '',
	'buttonBgColor'           => '#9d9d9d',
	'buttonBgHoverColor'      => '',
	'buttonIconColor'         => '',
	'buttonIconHoverColor'    => '',
	'buttonWidth'             => 55,
	'buttonIconSize'          => 17,
	'iconColor'               => '',
	'iconSize'                => 17,
	'inputloadGoogleFonts'    => false,
	'inputFontFamily'         => 'Default',
	'inputFontWeight'         => '',
	'inputFontSubset'         => '',
	'inputFontSize'           => '',
	'inputFontSizeType'       => 'px',
	'inputFontSizeTablet'     => '',
	'inputFontSizeMobile'     => '',
	'inputLineHeight'         => '',
	'inputLineHeightType'     => 'em',
	'inputLineHeightTablet'   => '',
	'inputLineHeightMobile'   => '',
	'inputPaddingTypeDesktop' => 'px',
	'vinputPaddingMobile'     => 15,
	'vinputPaddingTablet'     => 15,
	'vinputPaddingDesktop'    => 15,
	'hinputPaddingMobile'     => 13,
	'hinputPaddingTablet'     => 13,
	'hinputPaddingDesktop'    => 13,
	'buttonType'              => 'icon',
	'buttonText'              => 'Search',
	'buttonloadGoogleFonts'   => 'false',
	'buttonFontFamily'        => 'Default',
	'buttonFontWeight'        => '',
	'buttonFontSubset'        => '',
	'buttonFontSize'          => '',
	'buttonFontSizeType'      => 'px',
	'buttonFontSizeTablet'    => '',
	'buttonFontSizeMobile'    => '',
	'buttonLineHeight'        => '',
	'buttonLineHeightType'    => 'em',
	'buttonLineHeightTablet'  => '',
	'buttonLineHeightMobile'  => '',
	'buttonTextColor'         => '#313131',
	'buttonTextHoverColor'    => '',
	'inputSizeType'           => '%',
	'mobilePaddingInputUnit'  => 'px',
	'tabletPaddingInputUnit'  => 'px',
	'spacingLink'             => '',
	'iconSizeType'            => 'px',
	'inputTransform'          => '',
	'inputDecoration'         => '',
	'buttonTransform'         => '',
	'buttonDecoration'        => '',
	'borderHColor'            => '',
	'buttonIconSizeType'      => 'px',
	'buttonWidthType'         => 'px',
);
