<?php
/**
 * Attributes File.
 *
 * @since 2.0.0
 *
 * @package uagb
 */

return array(
	'block_id'                => '',
	'overallAlignment'        => 'left',
	'tools_count'             => 1,
	'material_count'          => 1,
	'tools'                   => '',
	'materials'               => '',
	'showTotaltime'           => true,
	'showEstcost'             => true,
	'showTools'               => true,
	'showMaterials'           => true,
	'mainimage'               => '',
	'imgSize'                 => 'thumbnail',
	'timeSpace'               => 5,
	'costSpace'               => 5,
	'time'                    => '30',
	'cost'                    => '65',
	'currencyType'            => ' USD',
	'headingAlign'            => 'left',
	'descriptionAlign'        => 'left',
	'headingColor'            => '',
	'showEstcostcolor'        => '',
	'showTotaltimecolor'      => '',
	'subHeadingColor'         => '',
	'headingTag'              => 'h3',
	'headSpace'               => 15,
	'headFontFamily'          => 'Default',
	'headFontWeight'          => '',
	'headFontStyle'           => '',
	'headFontSizeType'        => 'px',
	'headLineHeightType'      => 'em',
	'headFontSize'            => '',
	'headFontSizeTablet'      => '',
	'headFontSizeMobile'      => '',
	'headLineHeight'          => '',
	'headLineHeightTablet'    => '',
	'headLineHeightMobile'    => '',
	'subHeadFontFamily'       => 'Default',
	'subHeadFontWeight'       => '',
	'subHeadFontStyle'        => '',
	'subHeadFontSize'         => '',
	'subHeadFontSizeType'     => 'px',
	'subHeadFontSizeTablet'   => '',
	'subHeadFontSizeMobile'   => '',
	'subHeadLineHeight'       => '',
	'subHeadLineHeightType'   => 'em',
	'subHeadLineHeightTablet' => '',
	'subHeadLineHeightMobile' => '',
	'separatorSpace'          => 15,
	'headLoadGoogleFonts'     => false,
	'subHeadLoadGoogleFonts'  => false,
	'priceFontSizeType'       => 'px',
	'priceFontSize'           => '',
	'priceFontSizeTablet'     => '',
	'priceFontSizeMobile'     => '',
	'priceFontFamily'         => 'Default',
	'priceFontWeight'         => '',
	'priceFontStyle'          => '',
	'priceLineHeightType'     => 'em',
	'priceLineHeight'         => '',
	'priceLineHeightTablet'   => '',
	'priceLineHeightMobile'   => '',
	'priceLoadGoogleFonts'    => false,
	'row_gap'                 => 20,
	'step_gap'                => '',
	'schema'                  => '',
	'headTransform'           => '',
	'headDecoration'          => '',
	'subHeadTransform'        => '',
	'subHeadDecoration'       => '',
	'priceTransform'          => '',
	'priceDecoration'         => '',
);
