<?php
/**
 * Block Information & Attributes File.
 *
 * @since x.x.x
 *
 * @package uagb
 */

$block_slug = 'uagb/how-to';
$block_data = array(
	'doc'              => 'how-to-schema',
	'slug'             => '',
	'admin_categories' => array( 'seo' ),
	'link'             => 'how-to-schema',
	'title'            => __( 'How-to Schema', 'ultimate-addons-for-gutenberg' ),
	'description'      => __( 'This block allows you to design attractive How-to pages or articles with automatically adding How-to Schema to your page.', 'ultimate-addons-for-gutenberg' ),
	'default'          => true,
	'extension'        => false,
	'attributes'       => array(
		'block_id'                => '',
		'overallAlignment'        => 'left',
		'tools_count'             => 1,
		'material_count'          => 1,
		'tools'                   => '',
		'materials'               => '',
		'showTotaltime'           => true,
		'showEstcost'             => true,
		'showTools'               => true,
		'showMaterials'           => true,
		'mainimage'               => '',
		'imgSize'                 => 'thumbnail',
		'timeSpace'               => 5,
		'costSpace'               => 5,
		'time'                    => '30',
		'cost'                    => '65',
		'currencyType'            => ' USD',
		'headingAlign'            => 'left',
		'descriptionAlign'        => 'left',
		'headingColor'            => '',
		'showEstcostcolor'        => '',
		'showTotaltimecolor'      => '',
		'subHeadingColor'         => '',
		'headingTag'              => 'h3',
		'headSpace'               => 15,
		'headFontFamily'          => 'Default',
		'headFontWeight'          => '',
		'headFontSubset'          => '',
		'headFontSizeType'        => 'px',
		'headLineHeightType'      => 'em',
		'headFontSize'            => '',
		'headFontSizeTablet'      => '',
		'headFontSizeMobile'      => '',
		'headLineHeight'          => '',
		'headLineHeightTablet'    => '',
		'headLineHeightMobile'    => '',
		'subHeadFontFamily'       => 'Default',
		'subHeadFontWeight'       => '',
		'subHeadFontSubset'       => '',
		'subHeadFontSize'         => '',
		'subHeadFontSizeType'     => 'px',
		'subHeadFontSizeTablet'   => '',
		'subHeadFontSizeMobile'   => '',
		'subHeadLineHeight'       => '',
		'subHeadLineHeightType'   => 'em',
		'subHeadLineHeightTablet' => '',
		'subHeadLineHeightMobile' => '',
		'separatorSpace'          => 15,
		'headLoadGoogleFonts'     => false,
		'subHeadLoadGoogleFonts'  => false,
		'priceFontSizeType'       => 'px',
		'priceFontSize'           => '',
		'priceFontSizeTablet'     => '',
		'priceFontSizeMobile'     => '',
		'priceFontFamily'         => 'Default',
		'priceFontWeight'         => '',
		'priceFontSubset'         => '',
		'priceLineHeightType'     => 'em',
		'priceLineHeight'         => '',
		'priceLineHeightTablet'   => '',
		'priceLineHeightMobile'   => '',
		'priceLoadGoogleFonts'    => false,
		'row_gap'                 => 20,
		'step_gap'                => '',
		'schema'                  => '',
	),
);
