<?php
/**
 * Block Information & Attributes File.
 *
 * @since x.x.x
 *
 * @package uagb
 */

return array(
	'classMigrate'             => false,
	'block_id '                => '',
	'skinStyle'                => 'border',
	'align'                    => 'left',
	'descColor'                => '',
	'descFontSize'             => 18,
	'descFontSizeType'         => 'px',
	'descFontSizeTablet'       => '',
	'descFontSizeMobile'       => '',
	'descFontFamily'           => '',
	'descFontWeight'           => '',
	'descFontSubset'           => '',
	'descLineHeightType'       => 'em',
	'descLineHeight'           => 1.5,
	'descLineHeightTablet'     => '',
	'descLineHeightMobile'     => '',
	'descLoadGoogleFonts'      => false,
	'descSpace'                => 25,
	'authorColor'              => '#888888',
	'authorFontSize'           => '',
	'authorFontSizeType'       => 'px',
	'authorFontSizeTablet'     => '',
	'authorFontSizeMobile'     => '',
	'authorFontFamily'         => '',
	'authorFontWeight'         => '',
	'authorFontSubset'         => '',
	'authorLineHeightType'     => 'em',
	'authorLineHeight'         => '',
	'authorLineHeightTablet'   => '',
	'authorLineHeightMobile'   => '',
	'authorLoadGoogleFonts'    => false,
	'authorSpace'              => 10,
	'authorImageWidth'         => 40,
	'authorImgBorderRadius'    => 100,
	'authorImgPosition'        => 'left',
	'stack'                    => 'tablet',
	'enableTweet'              => true,
	'iconView'                 => 'icon_text',
	'iconSkin'                 => 'classic',
	'tweetLinkColor'           => '#1DA1F2',
	'tweetBtnColor'            => '#fff',
	'tweetBtnBgColor'          => '#1DA1F2',
	'tweetBtnHoverColor'       => '',
	'tweetBtnBgHoverColor'     => '#1DA1F2',
	'tweetBtnFontSize'         => 15,
	'tweetBtnFontSizeType'     => 'px',
	'tweetBtnFontSizeTablet'   => '',
	'tweetBtnFontSizeMobile'   => '',
	'tweetBtnFontFamily'       => '',
	'tweetBtnFontWeight'       => '',
	'tweetBtnFontSubset'       => '',
	'tweetBtnLineHeightType'   => 'em',
	'tweetBtnLineHeight'       => '',
	'tweetBtnLineHeightTablet' => '',
	'tweetBtnLineHeightMobile' => '',
	'tweetBtnLoadGoogleFonts'  => false,
	'tweetBtnHrPadding'        => 10,
	'tweetBtnVrPadding'        => 10,
	'tweetIconSpacing'         => 10,
	'borderColor'              => '#abb8c3',
	'borderStyle'              => 'solid',
	'borderWidth'              => 4,
	'borderGap'                => 15,
	'verticalPadding'          => '',
	'quoteStyle'               => 'style_2',
	'quoteColor'               => '#3d3d3d',
	'quoteSize'                => 25,
	'quoteSizeType'            => 'px',
	'quoteSizeTablet'          => '',
	'quoteSizeMobile'          => '',
	'quoteTopMargin'           => '',
	'quoteBottomMargin'        => '',
	'quoteLeftMargin'          => '',
	'quoteRightMargin'         => 20,
	'quoteBorderRadius'        => 100,
	'quoteBgColor'             => '#f4f4f4',
	'quoteHoverColor'          => '',
	'quoteBgHoverColor'        => '',
	'borderHoverColor'         => '',
	'iconTargetUrl'            => 'current',
	'customUrl'                => '',
	'iconShareVia'             => '',
	'quotePadding'             => 10,
	'quotePaddingType'         => 'px',
	'quotePaddingTablet'       => '',
	'quotePaddingMobile'       => '',
	'descriptionText'          => 'Click here to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.',
);
