<?php
/**
 * Block Information & Attributes File.
 *
 * @since x.x.x
 *
 * @package uagb
 */

$block_slug = 'uagb/marketing-button';
$block_data = array(
	'slug'        => '',
	'title'       => __( 'Marketing Button', 'ultimate-addons-for-gutenberg' ),
	'description' => __( 'This block allows you to place a Marketing Button with small description.', 'ultimate-addons-for-gutenberg' ),
	'default'     => true,
	'extension'   => false,
	'attributes'  => array(
		'classMigrate'           => false,
		'block_id'               => '',
		'align'                  => 'center',
		'textAlign'              => 'center',
		'link'                   => '#',
		'linkTarget'             => false,
		'titleSpace'             => 0,
		'borderStyle'            => 'solid',
		'borderWidth'            => 1,
		'borderRadius'           => '',
		'borderColor'            => '#333',
		'borderHoverColor'       => '',
		'vPadding'               => 8,
		'hPadding'               => 20,
		'vPaddingMobile'         => '',
		'hPaddingMobile'         => '',
		'vPaddingTablet'         => '',
		'hPaddingTablet'         => '',
		'paddingType'            => 'px',
		'backgroundType'         => 'color',
		'backgroundColor'        => '#eeeeee',
		'backgroundHoverColor'   => '',
		'gradientColor1'         => '',
		'gradientColor2'         => '',
		'gradientType'           => 'linear',
		'gradientLocation1'      => 0,
		'gradientLocation2'      => 100,
		'gradientAngle'          => 0,
		'backgroundOpacity'      => '',
		'backgroundHoverOpacity' => '',
		'titleColor'             => '#333',
		'titleHoverColor'        => '',
		'iconColor'              => '#333',
		'iconHoverColor'         => '',
		'iconPosition'           => 'before',
		'prefixColor'            => '#333',
		'prefixHoverColor'       => '',
		'iconSpace'              => 10,
		'titleLoadGoogleFonts'   => false,
		'titleFontFamily'        => '',
		'titleFontWeight'        => '',
		'titleFontSubset'        => '',
		'titleFontSize'          => 20,
		'titleFontSizeType'      => 'px',
		'titleFontSizeTablet'    => 20,
		'titleFontSizeMobile'    => 20,
		'titleLineHeightType'    => 'em',
		'titleLineHeight'        => '',
		'titleLineHeightTablet'  => '',
		'titleLineHeightMobile'  => '',
		'titleTag'               => 'h6',
		'prefixLoadGoogleFonts'  => false,
		'prefixFontFamily'       => '',
		'prefixFontWeight'       => '',
		'prefixFontSubset'       => '',
		'prefixFontSize'         => 14,
		'prefixFontSizeType'     => 'px',
		'prefixFontSizeTablet'   => 14,
		'prefixFontSizeMobile'   => 14,
		'prefixLineHeightType'   => 'em',
		'prefixLineHeight'       => '',
		'prefixLineHeightTablet' => '',
		'prefixLineHeightMobile' => '',
		'iconFontSize'           => 20,
		'iconFontSizeType'       => 'px',
		'iconFontSizeTablet'     => 20,
		'iconFontSizeMobile'     => 20,
		'paddingBtnUnit'         => 'px',
		'mobilePaddingBtnUnit'   => 'px',
		'tabletPaddingBtnUnit'   => 'px',
	),
);
