<?php
/**
 * Block Information & Attributes File.
 *
 * @since x.x.x
 *
 * @package uagb
 */

$block_slug = 'uagb/call-to-action';
$block_data = array(
	'slug'        => '',
	'title'       => __( 'Call To Action', 'ultimate-addons-for-gutenberg' ),
	'description' => __( 'This block allows you to place an CTA along with a heading and description within a single block.', 'ultimate-addons-for-gutenberg' ),
	'default'     => true,
	'extension'   => false,
	'attributes'  => array(
		'classMigrate'           => false,
		'inheritFromTheme'       => false,
		'textAlign'              => 'left',
		'titleColor'             => '',
		'descColor'              => '',
		'ctaPosition'            => 'right',
		'titleTag'               => '',
		'titleFontSize'          => '',
		'titleFontSizeType'      => 'px',
		'titleFontSizeMobile'    => '',
		'titleFontSizeTablet'    => '',
		'titleFontFamily'        => '',
		'titleFontWeight'        => '',
		'titleFontSubset'        => '',
		'titleLineHeightType'    => 'em',
		'titleLineHeight'        => '',
		'titleLineHeightTablet'  => '',
		'titleLineHeightMobile'  => '',
		'titleLoadGoogleFonts'   => false,
		'descFontSize'           => '',
		'descFontSizeType'       => 'px',
		'descFontSizeMobile'     => '',
		'descFontSizeTablet'     => '',
		'descFontFamily'         => '',
		'descFontWeight'         => '',
		'descFontSubset'         => '',
		'descLineHeightType'     => 'em',
		'descLineHeight'         => '',
		'descLineHeightTablet'   => '',
		'descLineHeightMobile'   => '',
		'descLoadGoogleFonts'    => false,
		'titleSpace'             => 10,
		'descSpace'              => 10,
		'buttonAlign'            => 'top',
		'ctaTarget'              => false,
		'ctaIconPosition'        => 'after',
		'ctaIconSpace'           => 5,
		'ctaType'                => 'button',
		'ctaLink'                => '#',
		'ctaFontSize'            => '',
		'ctaFontSizeType'        => 'px',
		'ctaFontSizeMobile'      => '',
		'ctaFontSizeTablet'      => '',
		'ctaFontFamily'          => '',
		'ctaFontWeight'          => '',
		'ctaFontSubset'          => '',
		'ctaLoadGoogleFonts'     => false,
		'ctaBtnLinkColor'        => '#333',
		'ctaBgColor'             => 'transparent',
		'ctaBgHoverColor'        => 'transparent',
		'ctaBorderColor'         => '#333',
		'ctaBorderhoverColor'    => '',
		'ctaBorderStyle'         => 'solid',
		'ctaBtnVertPadding'      => 10,
		'ctaBtnHrPadding'        => 14,
		'ctaBorderWidth'         => 1,
		'ctaBorderRadius'        => 0,
		'stack'                  => 'tablet',
		'showTitle'              => true,
		'showDesc'               => true,
		'ctaLeftSpace'           => 5,
		'ctaRightSpace'          => 5,
		'contentWidth'           => 70,
		'ctaLinkHoverColor'      => '',
		'ctaTopPaddingTablet'    => '',
		'ctaRightPaddingTablet'  => '',
		'ctaBottomPaddingTablet' => '',
		'ctaLeftPaddingTablet'   => '',
		'ctaTopPaddingMobile'    => '',
		'ctaRightPaddingMobile'  => '',
		'ctaBottomPaddingMobile' => '',
		'ctaLeftPaddingMobile'   => '',
		'ctaPaddingUnit'         => 'px',
		'mobileCTAPaddingUnit'   => 'px',
		'tabletCTAPaddingUnit'   => 'px',
		'ctaPaddingLink'         => '',
	),
);
