export const SET_OPEN_AI_API_KEY_AI_STEP = 'SET_OPEN_AI_API_KEY_AI_STEP';
export const SET_WEBSITE_TYPE_AI_STEP = 'SET_WEBSITE_TYPE_AI_STEP';
export const SET_WEBSITE_NAME_AI_STEP = 'SET_WEBSITE_NAME_AI_STEP';
export const SET_WEBSITE_DETAILS_AI_STEP = 'SET_WEBSITE_DETAILS_AI_STEP';
export const SET_WEBSITE_DETAILS_HISTORY_AI_STEP = 'SET_WEBSITE_DETAILS_HISTORY_AI_STEP';
export const SET_WEBSITE_KEYWORDS_AI_STEP = 'SET_WEBSITE_KEYWORDS_AI_STEP';
export const SET_WEBSITE_IMAGES_AI_STEP = 'SET_WEBSITE_IMAGES_AI_STEP';
export const SET_WEBSITE_IMAGES_PRE_SELECTED_AI_STEP =
	'SET_WEBSITE_IMAGES_PRE_SELECTED_AI_STEP';
export const RESET_KEYWORDS_IMAGES_AI_STEP = 'RESET_KEYWORDS_IMAGES_AI_STEP';
export const SET_WEBSITE_CONTACT_AI_STEP = 'SET_WEBSITE_CONTACT_AI_STEP';
export const SET_PREVIOUS_AI_STEP = 'SET_PREVIOUS_AI_STEP';
export const SET_NEXT_AI_STEP = 'SET_NEXT_AI_STEP';
export const TOGGLE_ONBOARDING_AI_STEP = 'TOGGLE_ONBOARDING_AI_STEP';
export const RESET_ONBOARDING_AI_STEPS = 'RESET_ONBOARDING_AI_STEPS';
export const TOGGLE_DISABLE_AI_CONTENT = 'TOGGLE_DISABLE_AI_CONTENT';
export const TOGGLE_ADAPTIVE_MODE = 'TOGGLE_ADAPTIVE_MODE';
export const TOGGLE_DISABLE_LIVE_PREVIEW = 'TOGGLE_DISABLE_LIVE_PREVIEW';
export const DYNAMIC_CONTENT_SYNC_START = 'DYNAMIC_CONTENT_SYNC_START';
export const DYNAMIC_CONTENT_SYNC_COMPLETE = 'DYNAMIC_CONTENT_SYNC_COMPLETE';
export const DYNAMIC_CONTENT_RESYNC_STATUS = 'DYNAMIC_CONTENT_RESYNC_STATUS';
export const DYNAMIC_CONTENT_FLAG_SET = 'DYNAMIC_CONTENT_FLAG_SET';
export const DYNAMIC_CONTENT_FLAGS_RESET = 'DYNAMIC_CONTENT_FLAGS_RESET';
export const SET_DYNAMIC_CONTENT = 'SET_DYNAMIC_CONTENT';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_IMPORT_IN_PROGRESS = 'SET_IMPORT_IN_PROGRESS';
export const SET_SHOW_PAGES_ONBOARDING = 'SET_SHOW_PAGES_ONBOARDING';
export const SET_CREDITS_DETAILS = 'SET_CREDITS_DETAILS';
export const TOGGLE_ONBOARDING_PAGE_AI = 'TOGGLE_ONBOARDING_PAGE_AI';
export const SET_NEXT_ONBOARDING_PAGE_AI_STEP =
	'SET_NEXT_ONBOARDING_PAGE_AI_STEP';
export const SET_PREVIOUS_ONBOARDING_PAGE_AI_STEP =
	'SET_PREVIOUS_ONBOARDING_PAGE_AI_STEP';
export const SET_IS_NEW_USER_ONBOARDING = 'SET_IS_NEW_USER_ONBOARDING';
export const TOGGLE_UPDATE_ONBOARDING_IMAGES =
	'TOGGLE_UPDATE_ONBOARDING_IMAGES';
export const DYNAMIC_CONTENT_SYNC_MESSAGE = 'DYNAMIC_CONTENT_SYNC_MESSAGE';
export const TOGGLE_SKIP_ZIP_AI_ONBOARDING = 'TOGGLE_SKIP_ZIP_AI_ONBOARDING';
export const SET_FILTER_SITES_BY_SEARCH_TERM = 'SET_FILTER_SITES_BY_SEARCH_TERM';
export const SET_FILTER_SITES_BY_CATEGORY = 'SET_FILTER_SITES_BY_CATEGORY';
export const UPDATE_LICENSE_STATUS = 'UPDATE_LICENSE_STATUS';
export const SET_ALL_SITES = 'SET_ALL_SITES';
export const TOGGLE_CONNECT_ZIP_AI = 'TOGGLE_CONNECT_ZIP_AI';
export const SET_HIDE_NOTICE = 'SET_HIDE_NOTICE';
export const SET_WEBSITE_TYPE_LIST_AI_STEP = 'SET_WEBSITE_TYPE_LIST_AI_STEP';
export const FETCH_FROM_API = 'FETCH_FROM_API';
export const SET_LOADING_BLOCKS_AND_SITES = 'SET_LOADING_BLOCKS_AND_SITES';
