<?php
/**
 * Block Information & Attributes File.
 *
 * @since x.x.x
 *
 * @package uagb
 */

$block_slug = 'uagb/post-masonry';
$block_data = array(
	'doc'              => 'post-masonry',
	'slug'             => '',
	'admin_categories' => array( 'creative', 'post' ),
	'link'             => 'post-layouts',
	'title'            => __( 'Post Masonry', 'ultimate-addons-for-gutenberg' ),
	'description'      => __( 'This block fetches the blog posts you may have on your website and displays them in a masonry layout.', 'ultimate-addons-for-gutenberg' ),
	'default'          => true,
	'extension'        => false,
	'js_assets'        => array( 'uagb-masonry', 'uagb-imagesloaded', 'uagb-post-js' ),
	'attributes'       => array(
		'post_type'                         => 'masonry',
		'postType'                          => 'post',
		'inheritFromTheme'                  => false,
		'align'                             => 'left',
		'rowGap'                            => '20',
		'columnGap'                         => '20',
		'bgColor'                           => '#e4e4e4',
		'titleColor'                        => '#3b3b3b',
		'titleTag'                          => 'h3',
		'titleFontSize'                     => '',
		'titleFontSizeType'                 => 'px',
		'titleFontSizeMobile'               => '',
		'titleFontSizeTablet'               => '',
		'titleFontFamily'                   => '',
		'titleFontWeight'                   => '',
		'titleFontSubset'                   => '',
		'titleLineHeightType'               => 'em',
		'titleLineHeight'                   => '',
		'titleLineHeightTablet'             => '',
		'titleLineHeightMobile'             => '',
		'titleLoadGoogleFonts'              => false,
		'metaFontSize'                      => '',
		'metaFontSizeType'                  => 'px',
		'metaFontSizeMobile'                => '',
		'metaFontSizeTablet'                => '',
		'metaFontFamily'                    => '',
		'metaFontWeight'                    => '',
		'metaFontSubset'                    => '',
		'metaLineHeightType'                => 'em',
		'metaLineHeight'                    => '',
		'metaLineHeightTablet'              => '',
		'metaLineHeightMobile'              => '',
		'metaLoadGoogleFonts'               => false,
		'excerptFontSize'                   => '',
		'excerptFontSizeType'               => 'px',
		'excerptFontSizeMobile'             => '',
		'excerptFontSizeTablet'             => '',
		'excerptFontFamily'                 => '',
		'excerptFontWeight'                 => '',
		'excerptFontSubset'                 => '',
		'excerptLineHeightType'             => 'em',
		'excerptLineHeight'                 => '',
		'excerptLineHeightTablet'           => '',
		'excerptLineHeightMobile'           => '',
		'excerptLoadGoogleFonts'            => false,
		'ctaFontSize'                       => '',
		'ctaFontSizeType'                   => 'px',
		'ctaFontSizeTablet'                 => '',
		'ctaFontSizeMobile'                 => '',
		'ctaFontFamily'                     => '',
		'ctaFontWeight'                     => '',
		'ctaFontSubset'                     => '',
		'ctaLineHeightType'                 => 'em',
		'ctaLineHeight'                     => '',
		'ctaLineHeightTablet'               => '',
		'ctaLineHeightMobile'               => '',
		'ctaLoadGoogleFonts'                => false,
		'metaColor'                         => '#777777',
		'excerptColor'                      => '',
		'ctaColor'                          => '#ffffff',
		'ctaBgColor'                        => '#333333',
		'ctaHColor'                         => '',
		'ctaBgHColor'                       => '',
		'contentPadding'                    => '20',
		'contentPaddingMobile'              => '',
		'btnVPadding'                       => '5',
		'btnHPadding'                       => '10',
		'ctaBottomSpace'                    => '0',
		'imageBottomSpace'                  => '15',
		'titleBottomSpace'                  => '15',
		'metaBottomSpace'                   => '15',
		'excerptBottomSpace'                => '25',
		'overlayOpacity'                    => '50',
		'bgOverlayColor'                    => '#ffffff',
		'ctaText'                           => __( 'Read More', 'ultimate-addons-for-gutenberg' ),
		'borderWidth'                       => '1',
		'borderStyle'                       => 'none',
		'borderColor'                       => '',
		'borderHColor'                      => '',
		'borderRadius'                      => '0',
		'paginationType'                    => 'none',
		'paginationEventType'               => 'button',
		'buttonText'                        => 'Load More',
		'paginationAlign'                   => 'center',
		'paginationTextColor'               => '',
		'paginationMasonryBgColor'          => '',
		'paginationBgHoverColor'            => '',
		'paginationTextHoverColor'          => '',
		'paginationMasonryBorderStyle'      => 'solid',
		'paginationMasonryBorderWidth'      => 1,
		'paginationMasonryBorderRadius'     => 2,
		'paginationMasonryBorderColor'      => '',
		'paginationFontSize'                => 13,
		'loaderColor'                       => '#0085ba',
		'loaderSize'                        => 18,
		'vpaginationButtonPaddingMobile'    => 8,
		'vpaginationButtonPaddingTablet'    => 8,
		'vpaginationButtonPaddingDesktop'   => 8,
		'hpaginationButtonPaddingMobile'    => 12,
		'hpaginationButtonPaddingTablet'    => 12,
		'hpaginationButtonPaddingDesktop'   => 12,
		'imgPosition'                       => 'top',

		'mobilepaginationButtonPaddingType' => 'px',
		'tabletpaginationButtonPaddingType' => 'px',
		'paginationButtonPaddingType'       => 'px',
		'displayPostContentRadio'           => 'excerpt',
		'excludeCurrentPost'                => '',
		'rowGapUnit'                        => 'px',
		'columnGapUnit'                     => 'px',
		'contentPaddingUnit'                => 'px',
		'excerptBottomSpaceUnit'            => 'px',
		'paginationSpacingUnit'             => 'px',
		'imageBottomSpaceUnit'              => 'px',
		'titleBottomSpaceUnit'              => 'px',
		'metaBottomSpaceUnit'               => 'px',
		'ctaBottomSpaceUnit'                => 'px',
		'paddingBtnUnit'                    => 'px',
		'mobilePaddingBtnUnit'              => 'px',
		'tabletPaddingBtnUnit'              => 'px',
		'contentPaddingUnit'                => 'px',
		'paddingUnit'                       => 'px',
		'mobilePaddingUnit'                 => 'px',
		'tabletPaddingUnit'                 => 'px',
		'titleTransform'                    => '',
		'metaLinkTransform'                 => '',
		'excerptTransform'                  => '',
		'ctaTransform'                      => '',
		'titleDecoration'                   => '',
		'metaLinkDecoration'                => '',
		'excerptDecoration'                 => '',
		'ctaDecoration'                     => '',
		'paddingBtnTopTablet'               => '',
		'paddingBtnRightTablet'             => '',
		'paddingBtnBottomTablet'            => '',
		'paddingBtnLeftTablet'              => '',
		'paddingBtnTopMobile'               => '',
		'paddingBtnRightMobile'             => '',
		'paddingBtnBottomMobile'            => '',
		'paddingBtnLeftMobile'              => '',
		'spacingLink'                       => '',
		'spacingLinkPadding'                => '',
		'paddingTopTablet'                  => '',
		'paddingRightTablet'                => '',
		'paddingBottomTablet'               => '',
		'paddingLeftTablet'                 => '',
		'paddingTopMobile'                  => '',
		'paddingRightMobile'                => '',
		'paddingBottomMobile'               => '',
		'paddingLeftMobile'                 => '',
		'layoutConfig'                      => array(
			array( 'uagb/post-image' ),
			array( 'uagb/post-title' ),
			array( 'uagb/post-meta' ),
			array( 'uagb/post-excerpt' ),
			array( 'uagb/post-button' ),
		),

	),
);
