<?php
/**
 * Attributes File.
 *
 * @since 2.0.0
 *
 * @package uagb
 */

return array(
	'block_id'                  => '',
	'layout'                    => '',
	'startNumber'               => 0,
	'endNumber'                 => 80,
	'totalNumber'               => 100,
	'numberPrefix'              => '',
	'numberSuffix'              => '',
	'animationDuration'         => 25,
	'thousandSeparator'         => '',
	// heading.
	'heading'                   => '',
	'headingTag'                => '',
	'headingFontFamily'         => 'Default',
	'headingFontWeight'         => '',
	'headingFontStyle'          => 'normal',
	'headingTransform'          => '',
	'headingFontSize'           => '',
	'headingColor'              => '#fff',
	'headingTransform'          => '',
	'headingDecoration'         => '',
	'headingFontSizeType'       => 'px',
	'headingFontSizeMobile'     => '',
	'headingFontSizeTablet'     => '',
	'headingLineHeight'         => 'em',
	'headingLineHeightType'     => 'em',
	'headingLineHeightMobile'   => '',
	'headingLineHeightTablet'   => '',
	'headingTopMargin'          => '',
	'headingRightMargin'        => '',
	'headingLeftMargin'         => '',
	'headingBottomMargin'       => '',
	'headingTopMarginTablet'    => '',
	'headingRightMarginTablet'  => '',
	'headingLeftMarginTablet'   => '',
	'headingBottomMarginTablet' => '',
	'headingTopMarginMobile'    => '',
	'headingRightMarginMobile'  => '',
	'headingLeftMarginMobile'   => '',
	'headingBottomMarginMobile' => '',
	'headingMarginUnit'         => 'px',
	'headingMarginUnitTablet'   => 'px',
	'headingMarginUnitMobile'   => 'px',
	// number.
	'numberColor'               => '',
	'numberFontFamily'          => '',
	'numberFontStyle'           => 'normal',
	'numberTransform'           => '',
	'numberDecoration'          => '',
	'numberFontSizeType'        => 'px',
	'numberLineHeightType'      => 'em',
	'numberFontSize'            => '',
	'numberFontWeight'          => '',
	'numberFontSizeTablet'      => '',
	'numberFontSizeMobile'      => '',
	'numberLineHeight'          => '',
	'numberLineHeightTablet'    => '',
	'numberLineHeightMobile'    => '',
	'numberTopMargin'           => '',
	'numberRightMargin'         => '',
	'numberLeftMargin'          => '',
	'numberBottomMargin'        => '',
	'numberTopMarginTablet'     => '',
	'numberRightMarginTablet'   => '',
	'numberLeftMarginTablet'    => '',
	'numberBottomMarginTablet'  => '',
	'numberTopMarginMobile'     => '',
	'numberRightMarginMobile'   => '',
	'numberLeftMarginMobile'    => '',
	'numberBottomMarginMobile'  => '',
	'numberMarginUnit'          => 'px',
	'numberMarginUnitTablet'    => 'px',
	'numberMarginUnitMobile'    => 'px',
	// Prefix.
	'prefixRightDistance'       => 5,
	// Suffix.
	'suffixLeftDistance'        => 5,
	// circle.
	'circleSize'                => 300,
	'circleStokeSize'           => 10,
	'circleForeground'          => '#eaeaea',
	'circleBackground'          => '#f7951e',
	// bar.
	'barSize'                   => 25,
	'barForeground'             => '#eaeaea',
	'barBackground'             => '#f7951e',
);
