<?php
/**
 * Attributes File.
 *
 * @since 2.0.0
 *
 * @package uagb
 */

return array(
	'classMigrate'              => false,
	'block_id'                  => '',
	'heading'                   => __( 'Table Of Contents', 'ultimate-addons-for-gutenberg' ),
	'emptyHeadingTeaxt'         => __( 'Add a header to begin generating the table of contents', 'ultimate-addons-for-gutenberg' ),
	'disableBullets'            => false,
	'smoothScroll'              => true,
	'smoothScrollOffset'        => 30,
	'scrollToTop'               => false,
	'scrollToTopColor'          => '',
	'scrollToTopBgColor'        => '',
	'considerH1'                => true,
	'considerH2'                => true,
	'considerH3'                => true,
	'considerH4'                => true,
	'considerH5'                => true,
	'considerH6'                => true,
	'customWidth'               => false,
	'widthDesktop'              => 100,
	'widthTablet'               => '',
	'widthMobile'               => '',
	'tColumnsDesktop'           => 1,
	'tColumnsTablet'            => 1,
	'tColumnsMobile'            => 1,
	'mappingHeaders'            => array_fill_keys( array( 0, 1, 2, 3, 4, 5 ), true ),
	'widthTypeDesktop'          => '%',
	'widthTypeTablet'           => '%',
	'widthTypeMobile'           => '%',
	'makeCollapsible'           => false,
	'initialCollapse'           => false,
	'icon'                      => 'fa-angle-down',
	'iconColor'                 => '',
	'bulletColor'               => '',
	'iconSize'                  => '',
	'align'                     => 'left',
	'linkColor'                 => '#54595F',
	'vPaddingDesktop'           => 30,
	'vPaddingTablet'            => '',
	'vPaddingMobile'            => '',
	'hPaddingDesktop'           => 30,
	'hPaddingTablet'            => '',
	'hPaddingMobile'            => '',
	'paddingTypeDesktop'        => 'px',
	'paddingTypeTablet'         => 'px',
	'paddingTypeMobile'         => 'px',
	'vMarginDesktop'            => '',
	'vMarginTablet'             => '',
	'vMarginMobile'             => '',
	'hMarginDesktop'            => '',
	'hMarginTablet'             => '',
	'hMarginMobile'             => '',
	'marginTypeDesktop'         => 'px',
	'marginTypeTablet'          => 'px',
	'marginTypeMobile'          => 'px',
	'contentPaddingDesktop'     => '',
	'contentPaddingTablet'      => '',
	'contentPaddingMobile'      => '',
	'contentPaddingTypeDesktop' => 'px',
	'contentPaddingTypeTablet'  => 'px',
	'contentPaddingTypeMobile'  => 'px',
	'headingBottom'             => '',
	'backgroundColor'           => '',
	'linkHoverColor'            => '',
	'headingColor'              => '',
	'borderStyle'               => 'solid',
	'borderWidth'               => '',
	'borderRadius'              => 6,
	'borderHoverColor'          => '',
	'borderColor'               => '',
	'loadGoogleFonts'           => false,
	'fontFamily'                => '',
	'fontWeight'                => '',
	'fontSize'                  => '',
	'fontSizeType'              => 'px',
	'fontSizeTablet'            => '',
	'fontSizeMobile'            => '',
	'lineHeightType'            => 'em',
	'lineHeight'                => '',
	'lineHeightTablet'          => '',
	'lineHeightMobile'          => '',
	'headingLoadGoogleFonts'    => false,
	'headingFontFamily'         => '',
	'headingFontWeight'         => '500',
	'headingFontSize'           => 20,
	'headingFontSizeType'       => 'px',
	'headingFontSizeTablet'     => '',
	'headingFontSizeMobile'     => '',
	'headingLineHeightType'     => 'em',
	'headingLineHeight'         => '',
	'headingLineHeightTablet'   => '',
	'headingLineHeightMobile'   => '',
	'fontStyle'                 => '',
	'fontTransform'             => '',
	'fontDecoration'            => 'underline',
	'headingFontStyle'          => '',
	'headingTransform'          => '',
	'headingDecoration'         => '',
);
