<?php
/**
 * Attributes File.
 *
 * @since 2.0.0
 *
 * @package uagb
 */

return array(
	'inheritFromTheme'     => false,
	'block_id'             => '',
	'label'                => '',
	'link'                 => '',
	'opensInNewTab'        => false,
	'target'               => '',
	'size'                 => '',
	'vPadding'             => '',
	'hPadding'             => '',
	'topTabletPadding'     => '',
	'rightTabletPadding'   => '',
	'bottomTabletPadding'  => '',
	'leftTabletPadding'    => '',
	'topMobilePadding'     => '',
	'rightMobilePadding'   => '',
	'bottomMobilePadding'  => '',
	'leftMobilePadding'    => '',
	'paddingUnit'          => 'px',
	'mobilePaddingUnit'    => 'px',
	'tabletPaddingUnit'    => 'px',
	'paddingLink'          => '',
	'borderWidth'          => '',
	'borderRadius'         => '',
	'borderStyle'          => '',
	'borderColor'          => '',
	'borderHColor'         => '',
	'color'                => '',
	'background'           => '',
	'hColor'               => '',
	'hBackground'          => '',
	'sizeType'             => 'px',
	'sizeMobile'           => '',
	'sizeTablet'           => '',
	'lineHeight'           => '',
	'lineHeightType'       => 'em',
	'lineHeightMobile'     => '',
	'lineHeightTablet'     => '',
	'icon'                 => '',
	'iconPosition'         => 'after',
	'iconSpace'            => 8,
	'LoadGoogleFonts'      => '',
	'fontFamily'           => '',
	'fontWeight'           => '',
	'fontStyle'            => '',
	'transform'            => '',
	'decoration'           => '',
	'gradientValue'        => '',
	'backgroundImageColor' => '',
	'backgroundSize'       => '',
	'backgroundRepeat'     => '',
	'backgroundAttachment' => '',
	'backgroundPosition'   => '',
	'backgroundImage'      => '',
	'backgroundType'       => '',
	'topMarginDesktop'     => '',
	'rightMarginDesktop'   => '',
	'bottomMarginDesktop'  => '',
	'leftMarginDesktop'    => '',
	'topMarginTablet'      => '',
	'rightMarginTablet'    => '',
	'bottomMarginTablet'   => '',
	'leftMarginTablet'     => '',
	'topMarginMobile'      => '',
	'rightMarginMobile'    => '',
	'bottomMarginMobile'   => '',
	'leftMarginMobile'     => '',
	'marginType'           => 'px',
	'marginLink'           => '',
	'boxShadowColor'       => '',
	'boxShadowHOffset'     => '',
	'boxShadowVOffset'     => '',
	'boxShadowBlur'        => '',
	'boxShadowSpread'      => '',
	'boxShadowPosition'    => '',
	'iconColor'            => '',
	'buttonSize'           => '',
	'removeText'           => true,
);
