<?php
/**
 * Attributes File.
 *
 * @since x.x.x
 *
 * @package uagb
 */

return array(
	'classMigrate'             => false,
	'block_id'                 => '',
	'topPadding'               => '',
	'bottomPadding'            => '',
	'leftPadding'              => '',
	'rightPadding'             => '',
	'topMargin'                => '',
	'bottomMargin'             => '',
	'leftMargin'               => '',
	'rightMargin'              => '',
	'topPaddingTablet'         => '',
	'bottomPaddingTablet'      => '',
	'leftPaddingTablet'        => '',
	'rightPaddingTablet'       => '',
	'topPaddingMobile'         => '',
	'bottomPaddingMobile'      => '',
	'leftPaddingMobile'        => '',
	'rightPaddingMobile'       => '',
	'topMarginMobile'          => '',
	'bottomMarginMobile'       => '',
	'leftMarginMobile'         => '',
	'rightMarginMobile'        => '',
	'topMarginTablet'          => '',
	'bottomMarginTablet'       => '',
	'leftMarginTablet'         => '',
	'rightMarginTablet'        => '',
	'colWidth'                 => '',
	'colWidthTablet'           => '',
	'colWidthMobile'           => '',
	'backgroundType'           => 'none',
	'backgroundImage'          => '',
	'backgroundPosition'       => 'center-center',
	'backgroundSize'           => 'cover',
	'backgroundRepeat'         => 'no-repeat',
	'backgroundAttachment'     => 'scroll',
	'backgroundColor'          => '',
	'gradientColor1'           => '',
	'gradientColor2'           => '',
	'gradientType'             => 'linear',
	'gradientLocation1'        => 0,
	'gradientLocation2'        => 100,
	'gradientAngle'            => 0,
	'backgroundOpacity'        => '',
	'backgroundImageColor'     => '',
	'borderStyle'              => 'none',
	'borderWidth'              => 1,
	'borderRadius'             => '',
	'borderColor'              => '',
	'borderHoverColor'         => '',
	'align'                    => 'center',
	'alignMobile'              => '',
	'alignTablet'              => '',
	'mobileMarginType'         => 'px',
	'tabletMarginType'         => 'px',
	'desktopMarginType'        => 'px',
	'mobilePaddingType'        => 'px',
	'tabletPaddingType'        => 'px',
	'desktopPaddingType'       => 'px',
	'overlayType'              => 'color',
	'gradientOverlayColor1'    => '',
	'gradientOverlayColor2'    => '',
	'gradientOverlayType'      => 'linear',
	'gradientOverlayLocation1' => '0',
	'gradientOverlayLocation2' => '100',
	'gradientOverlayAngle'     => '0',
	'gradientValue'            => '',
);
