<?php
/**
 * Attributes File.
 *
 * @since 2.0.0
 *
 * @package uagb
 */

$default_padding        = 20;
$border_attribute       = UAGB_Block_Helper::uag_generate_border_attribute( 'slider' );
$arrow_border_attribute = UAGB_Block_Helper::uag_generate_border_attribute( 'slider-arrow' );


return array_merge(
	array(
		'block_id'                    => '',
		'pauseOn'                     => 'hover',
		'infiniteLoop'                => true,
		'transitionSpeed'             => 800,
		'transitionEffect'            => 'slide',
		'autoplay'                    => true,
		'verticalMode'                => false,
		'autoplaySpeed'               => 1200,
		'displayArrows'               => true,
		'displayDots'                 => true,
		'backgroundType'              => 'none',
		'backgroundImageDesktop'      => '',
		'backgroundImageTablet'       => '',
		'backgroundImageMobile'       => '',
		'backgroundPositionDesktop'   => array(
			'x' => 0.5,
			'y' => 0.5,
		),
		'backgroundPositionTablet'    => '',
		'backgroundPositionMobile'    => '',
		'backgroundSizeDesktop'       => 'cover',
		'backgroundSizeTablet'        => '',
		'backgroundSizeMobile'        => '',
		'backgroundRepeatDesktop'     => 'no-repeat',
		'backgroundRepeatTablet'      => '',
		'backgroundRepeatMobile'      => '',
		'backgroundAttachmentDesktop' => 'scroll',
		'backgroundAttachmentTablet'  => '',
		'backgroundAttachmentMobile'  => '',
		'backgroundColor'             => '',
		'backgroundOpacity'           => '',
		'gradientValue'               => 'linear-gradient(90deg, rgba(6, 147, 227, 0.5) 0%, rgba(155, 81, 224, 0.5) 100%)',
		'backgroundImageColor'        => '#FFFFFF75',
		'backgroundCustomSizeDesktop' => 100,
		'backgroundCustomSizeTablet'  => '',
		'backgroundCustomSizeMobile'  => '',
		'backgroundCustomSizeType'    => '%',
		'overlayType'                 => 'none',
		'customPosition'              => 'default',
		'xPositionDesktop'            => '',
		'xPositionTablet'             => '',
		'xPositionMobile'             => '',
		'xPositionType'               => 'px',
		'xPositionTypeTablet'         => 'px',
		'xPositionTypeMobile'         => 'px',
		'yPositionDesktop'            => '',
		'yPositionTablet'             => '',
		'yPositionMobile'             => '',
		'yPositionType'               => 'px',
		'yPositionTypeTablet'         => 'px',
		'yPositionTypeMobile'         => 'px',
		'topPaddingDesktop'           => $default_padding,
		'bottomPaddingDesktop'        => $default_padding,
		'leftPaddingDesktop'          => $default_padding,
		'rightPaddingDesktop'         => $default_padding,
		'topPaddingTablet'            => $default_padding,
		'bottomPaddingTablet'         => $default_padding,
		'leftPaddingTablet'           => $default_padding,
		'rightPaddingTablet'          => $default_padding,
		'topPaddingMobile'            => $default_padding,
		'bottomPaddingMobile'         => $default_padding,
		'leftPaddingMobile'           => $default_padding,
		'rightPaddingMobile'          => $default_padding,
		'paddingType'                 => 'px',
		'paddingTypeTablet'           => 'px',
		'paddingTypeMobile'           => 'px',
		'paddingLink'                 => true,
		'topMarginDesktop'            => '',
		'bottomMarginDesktop'         => '',
		'leftMarginDesktop'           => '',
		'rightMarginDesktop'          => '',
		'topMarginTablet'             => '',
		'bottomMarginTablet'          => '',
		'leftMarginTablet'            => '',
		'rightMarginTablet'           => '',
		'topMarginMobile'             => '',
		'bottomMarginMobile'          => '',
		'leftMarginMobile'            => '',
		'rightMarginMobile'           => '',
		'marginType'                  => 'px',
		'marginTypeTablet'            => 'px',
		'marginTypeMobile'            => 'px',
		'boxShadowColor'              => '#00000070',
		'boxShadowHOffset'            => 0,
		'boxShadowVOffset'            => 0,
		'boxShadowBlur'               => '',
		'boxShadowSpread'             => '',
		'boxShadowPosition'           => 'outset',
		'boxShadowColorHover'         => '',
		'boxShadowHOffsetHover'       => 0,
		'boxShadowVOffsetHover'       => 0,
		'boxShadowBlurHover'          => '',
		'boxShadowSpreadHover'        => '',
		'boxShadowPositionHover'      => 'outset',
		'arrowSize'                   => 30,
		'arrowSizeTablet'             => '',
		'arrowSizeMobile'             => '',
		'arrowDistance'               => '',
		'arrowDistanceTablet'         => '',
		'arrowDistanceMobile'         => '',
		'arrowPadding'                => '20',
		'arrowPaddingTablet'          => '',
		'arrowPaddingMobile'          => '',
		'arrowColor'                  => '#000',
		'arrowBgColor'                => '',
		'verticalAlign'               => 'center',
		'dotsMarginTop'               => '10',
		'dotsMarginTopTablet'         => '',
		'dotsMarginTopMobile'         => '',
	),
	$border_attribute,
	$arrow_border_attribute
);
