<?php
/**
 * Block Information & Attributes File.
 *
 * @since x.x.x
 *
 * @package uagb
 */

$block_slug = 'uagb/restaurant-menu';
$block_data = array(
	'slug'        => '',
	'title'       => __( 'Price List', 'ultimate-addons-for-gutenberg' ),
	'description' => __( 'This block allows you to add attractive Price List.', 'ultimate-addons-for-gutenberg' ),
	'default'     => true,
	'extension'   => false,
	'attributes'  => array(
		'classMigrate'               => false,
		'block_id'                   => '',
		'headingAlign'               => 'left',
		'descColor'                  => '#333',
		'priceColor'                 => '#888888',
		'titleColor'                 => '#333',
		'imagePosition'              => 'top',
		'imageAlignment'             => 'top',
		'titleFontSize'              => '',
		'titleFontSizeType'          => 'px',
		'titleFontSizeMobile'        => '',
		'titleFontSizeTablet'        => '',
		'titleFontFamily'            => '',
		'titleFontWeight'            => '',
		'titleFontSubset'            => '',
		'titleLineHeightType'        => 'em',
		'titleLineHeight'            => '',
		'titleLineHeightTablet'      => '',
		'titleLineHeightMobile'      => '',
		'titleLoadGoogleFonts'       => false,
		'priceFontSize'              => '',
		'priceFontSizeType'          => 'px',
		'priceFontSizeMobile'        => '',
		'priceFontSizeTablet'        => '',
		'priceFontFamily'            => '',
		'priceFontWeight'            => '',
		'priceFontSubset'            => '',
		'priceLineHeightType'        => 'em',
		'priceLineHeight'            => '',
		'priceLineHeightTablet'      => '',
		'priceLineHeightMobile'      => '',
		'priceLoadGoogleFonts'       => false,
		'descFontSize'               => '',
		'descFontSizeType'           => 'px',
		'descFontSizeMobile'         => '',
		'descFontSizeTablet'         => '',
		'descFontFamily'             => '',
		'descFontWeight'             => '',
		'descFontSubset'             => '',
		'descLineHeightType'         => 'em',
		'descLineHeight'             => '',
		'descLineHeightTablet'       => '',
		'descLineHeightMobile'       => '',
		'descLoadGoogleFonts'        => false,
		'priceSpace'                 => 5,
		'descSpace'                  => 15,
		'titleSpace'                 => 10,
		'imgVrPadding'               => 0,
		'imgHrPadding'               => 0,
		'imgTopPadding'              => 0,
		'imgBottomPadding'           => 0,
		'iconImage'                  => '',
		'imageSize'                  => 'medium',
		'imageWidth'                 => '',
		'columns'                    => 2,
		'tcolumns'                   => 2,
		'mcolumns'                   => 1,
		'rowGap'                     => 10,
		'columnGap'                  => 10,
		'contentHrPadding'           => 5,
		'contentVrPadding'           => 5,
		'seperatorStyle'             => 'dashed',
		'seperatorWidth'             => '100',
		'seperatorThickness'         => '1',
		'seperatorColor'             => '#b2b4b5',
		'imageWidthType'             => 'px',
		'seperatorWidthType'         => '%',
		'rowGapType'                 => 'px',
		'columnGapType'              => 'px',
		'titleSpaceType'             => 'px',
		'contentPaddingTopTablet'    => '',
		'contentPaddingRightTablet'  => '',
		'contentPaddingBottomTablet' => '',
		'contentPaddingLeftTablet'   => '',
		'contentPaddingTopMobile'    => '',
		'contentPaddingRightMobile'  => '',
		'contentPaddingBottomMobile' => '',
		'contentPaddingLeftMobile'   => '',
		'contentPaddingUnit'         => 'px',
		'contentMobilePaddingUnit'   => 'px',
		'contentTabletPaddingUnit'   => 'px',
		'imgPaddingTopTablet'        => '',
		'imgPaddingRightTablet'      => '',
		'imgPaddingBottomTablet'     => '',
		'imgPaddingLeftTablet'       => '',
		'imgPaddingTopMobile'        => '',
		'imgPaddingRightMobile'      => '',
		'imgPaddingBottomMobile'     => '',
		'imgPaddingLeftMobile'       => '',
		'imgPaddingUnit'             => 'px',
		'imgMobilePaddingUnit'       => 'px',
		'imgTabletPaddingUnit'       => 'px',
		'titleTransform'             => '',
		'titleDecoration'            => '',
		'descTransform'              => '',
		'descDecoration'             => '',
		'priceTransform'             => '',
		'priceDecoration'            => '',
	),
);
