<?php
/**
 * Block Information & Attributes File.
 *
 * @since x.x.x
 *
 * @package uagb
 */

$button_attribute = UAGB_Block_Helper::uag_generate_border_attribute(
	'btn'
);

return array_merge(
	array(
		'modalTrigger'             => 'button',
		'buttonIconSpace'          => '5',
		'buttonIconSpaceTablet'    => '',
		'buttonIconSpaceMobile'    => '',
		'buttonIconSpaceType'      => 'px',
		'buttonIconPosition'       => 'after',
		'modalAlign'               => 'left',
		'modalAlignTablet'         => '',
		'modalAlignMobile'         => '',
		'modalWidth'               => 700,
		'modalWidthTablet'         => 700,
		'modalWidthMobile'         => 260,
		'modalWidthType'           => 'px',
		'modalHeight'              => 350,
		'modalHeightTablet'        => 350,
		'modalHeightMobile'        => 300,
		'modalHeightType'          => 'px',
		'closeIconSize'            => 25,
		'closeIconPosition'        => 'popup-top-right',
		'overlayColor'             => 'rgba(0,0,0,0.75)',
		'closeIconColor'           => '',
		'paddingModalUnit'         => 'px',
		'mobilePaddingModalUnit'   => 'px',
		'tabletPaddingModalUnit'   => 'px',
		'paddingModalTop'          => '',
		'paddingModalBottom'       => '',
		'paddingModalLeft'         => '',
		'paddingModalRight'        => '',
		'paddingModalTopTablet'    => '',
		'paddingModalRightTablet'  => '',
		'paddingModalBottomTablet' => '',
		'paddingModalLeftTablet'   => '',
		'paddingModalTopMobile'    => '',
		'paddingModalRightMobile'  => '',
		'paddingModalBottomMobile' => '',
		'paddingModalLeftMobile'   => '',

		'iconSize'                 => 30,
		'iconColor'                => '',
		'textColor'                => '',

		'textFontFamily'           => '',
		'textLoadGoogleFonts'      => false,
		'textFontWeight'           => '',
		'textFontStyle'            => '',
		'textFontSize'             => '',
		'textFontSizeType'         => 'px',
		'textFontSizeTablet'       => '',
		'textFontSizeMobile'       => '',
		'textSpaceType'            => 'px',
		'textLineHeight'           => '',
		'textLineHeightType'       => 'em',
		'textLineHeightTablet'     => '',
		'textLineHeightMobile'     => '',
		'textLetterSpacing'        => '',
		'textLetterSpacingTablet'  => '',
		'textLetterSpacingMobile'  => '',
		'textLetterSpacingType'    => 'px',
		'textTransform'            => '',
		'textDecoration'           => '',

		'imageSize'                => 'thumbnail',
		'imageWidthType'           => true,
		'imageWidth'               => '',
		'imageWidthMobile'         => '',
		'imageWidthTablet'         => '',
		'imageWidthUnit'           => 'px',
		'imageWidthUnitTablet'     => 'px',
		'imageWidthUnitMobile'     => 'px',
		'iconimgBorderRadius'      => '0',
		'iconimgBorderRadiusUnit'  => 'px',

		'paddingBtnUnit'           => 'px',
		'mobilePaddingBtnUnit'     => 'px',
		'tabletPaddingBtnUnit'     => 'px',
		'paddingBtnTop'            => '',
		'paddingBtnBottom'         => '',
		'paddingBtnLeft'           => '',
		'paddingBtnRight'          => '',
		'paddingBtnTopTablet'      => '',
		'paddingBtnRightTablet'    => '',
		'paddingBtnBottomTablet'   => '',
		'paddingBtnLeftTablet'     => '',
		'paddingBtnTopMobile'      => '',
		'paddingBtnRightMobile'    => '',
		'paddingBtnBottomMobile'   => '',
		'paddingBtnLeftMobile'     => '',

		'btnFontFamily'            => '',
		'btnLoadGoogleFonts'       => false,
		'btnFontWeight'            => '',
		'btnFontStyle'             => '',
		'btnFontSize'              => '',
		'btnFontSizeType'          => 'px',
		'btnFontSizeTablet'        => '',
		'btnFontSizeMobile'        => '',
		'btnSpaceType'             => 'px',
		'btnLineHeight'            => '',
		'btnLineHeightType'        => 'em',
		'btnLineHeightTablet'      => '',
		'btnLineHeightMobile'      => '',
		'btnLetterSpacing'         => '',
		'btnLetterSpacingTablet'   => '',
		'btnLetterSpacingMobile'   => '',
		'btnLetterSpacingType'     => 'px',
		'btnTransform'             => '',
		'btnDecoration'            => '',
		'btnLinkColor'             => '',
		'btnBgColor'               => '',
		'btnLinkHoverColor'        => '',
		'btnBgHoverColor'          => '',
		'modalBgColor'             => '',
	),
	$button_attribute
);
