<?php
/**
 * Block Information & Attributes File.
 *
 * @since x.x.x
 *
 * @package uagb
 */

return array(
	'modalTrigger'          => 'button',
	'buttonIconSpace'       => '5',
	'buttonIconSpaceTablet' => '',
	'buttonIconSpaceMobile' => '',
	'buttonIconSpaceType'   => 'px',
	'buttonIconPosition'    => 'after',
	'modalAlign'            => 'left',
	'modalAlignTablet'      => '',
	'modalAlignMobile'      => '',
	'modalWidth'            => 700,
	'modalWidthTablet'      => '',
	'modalWidthMobile'      => '',
	'modalWidthType'        => 'px',
	'modalHeight'           => 350,
	'modalHeightTablet'     => '',
	'modalHeightMobile'     => '',
	'modalHeightType'       => 'px',
	'closeIconSize'         => 25,
	'closeIconPosition'     => 'popup-top-right',
	'overlayColor'			=> 'rgba(0,0,0,0.75)',
	'paddingModalUnit'			=> 'px',
	'mobilePaddingModalUnit'			=> 'px',
	'tabletPaddingModalUnit'			=> 'px',
	'paddingModalTop'			=> '',
	'paddingModalBottom'			=> '',
	'paddingModalLeft'			=> '',
	'paddingModalRight'			=> '',
	'paddingModalTopTablet'			=> '',
	'paddingModalRightTablet'			=> '',
	'paddingModalBottomTablet'			=> '',
	'paddingModalLeftTablet'			=> '',
	'paddingModalTopMobile'			=> '',
	'paddingModalRightMobile'			=> '',
	'paddingModalBottomMobile'			=> '',
	'paddingModalLeftMobile'			=> '',
	// 'paddingBtnUnit'			=> 'px',
	// 'mobilePaddingBtnUnit'			=> 'px',
	// 'tabletPaddingBtnUnit'			=> 'px',
	// 'paddingBtnTop'			=> '',
	// 'paddingBtnBottom'			=> '',
	// 'paddingBtnLeft'			=> '',
	// 'paddingBtnRight'			=> '',
	// 'paddingBtnTopTablet'			=> '',
	// 'paddingBtnRightTablet'			=> '',
	// 'paddingBtnBottomTablet'			=> '',
	// 'paddingBtnLeftTablet'			=> '',
	// 'paddingBtnTopMobile'			=> '',
	// 'paddingBtnRightMobile'			=> '',
	// 'paddingBtnBottomMobile'			=> '',
	// 'paddingBtnLeftMobile'			=> '',
);
