<?php
/**
 * Block Information & Attributes File.
 *
 * @since 2.0.0
 *
 * @package uagb
 */

return array(
	'post_type'                   => 'grid',
	'align'                       => 'left',
	'rowGap'                      => '20',
	'columnGap'                   => '20',
	'bgColor'                     => '#f6f6f6',
	'titleColor'                  => '#3b3b3b',
	'titleTag'                    => 'h4',
	'titleFontSize'               => '',
	'titleFontSizeType'           => 'px',
	'titleFontSizeMobile'         => '',
	'titleFontSizeTablet'         => '',
	'titleFontFamily'             => '',
	'titleFontWeight'             => '',
	'titleFontStyle'              => '',
	'titleLineHeightType'         => 'em',
	'titleLineHeight'             => '',
	'titleLineHeightTablet'       => '',
	'titleLineHeightMobile'       => '',
	'titleLoadGoogleFonts'        => false,
	'metaFontSize'                => '',
	'metaFontSizeType'            => 'px',
	'metaFontSizeMobile'          => '',
	'metaFontSizeTablet'          => '',
	'metaFontFamily'              => '',
	'metaFontWeight'              => '',
	'metaFontStyle'               => '',
	'metaLineHeightType'          => 'em',
	'metaLineHeight'              => '',
	'metaLineHeightTablet'        => '',
	'metaLineHeightMobile'        => '',
	'metaLoadGoogleFonts'         => false,
	'excerptFontSize'             => '',
	'excerptFontSizeType'         => 'px',
	'excerptFontSizeMobile'       => '',
	'excerptFontSizeTablet'       => '',
	'excerptFontFamily'           => '',
	'excerptFontWeight'           => '',
	'excerptFontStyle'            => '',
	'excerptLineHeightType'       => 'em',
	'excerptLineHeight'           => '',
	'excerptLineHeightTablet'     => '',
	'excerptLineHeightMobile'     => '',
	'excerptLoadGoogleFonts'      => false,
	'ctaFontSize'                 => '',
	'ctaFontSizeType'             => 'px',
	'ctaFontSizeTablet'           => '',
	'ctaFontSizeMobile'           => '',
	'ctaFontFamily'               => '',
	'ctaFontWeight'               => '',
	'ctaFontStyle'                => '',
	'ctaLineHeightType'           => 'em',
	'ctaLineHeight'               => '',
	'ctaLineHeightTablet'         => '',
	'ctaLineHeightMobile'         => '',
	'ctaLoadGoogleFonts'          => false,
	'metaColor'                   => '',
	'excerptColor'                => '',
	'ctaColor'                    => '',
	'ctaBgColor'                  => '',
	'ctaHColor'                   => '',
	'ctaBgHColor'                 => '',
	'contentPadding'              => '20',
	'contentPaddingMobile'        => '',
	'btnVPadding'                 => '5',
	'btnHPadding'                 => '10',
	'ctaBottomSpace'              => '0',
	'imageBottomSpace'            => '15',
	'titleBottomSpace'            => '15',
	'metaBottomSpace'             => '15',
	'excerptBottomSpace'          => '25',
	'overlayOpacity'              => '50',
	'bgOverlayColor'              => '#ffffff',
	'ctaText'                     => __( 'Read More', 'ultimate-addons-for-gutenberg' ),
	'borderWidth'                 => '1',
	'borderStyle'                 => 'none',
	'borderColor'                 => '',
	'borderHColor'                => '',
	'borderRadius'                => '0',
	'postPagination'              => '',
	'pageLimit'                   => '',
	'paginationBgActiveColor'     => '#e4e4e4',
	'paginationActiveColor'       => '#333333',
	'paginationBgColor'           => '#e4e4e4',
	'paginationColor'             => '#777777',
	'paginationMarkup'            => '',
	'paginationLayout'            => 'filled',
	'paginationBorderActiveColor' => '',
	'paginationBorderColor'       => '#333',
	'paginationBorderRadius'      => '',
	'paginationBorderSize'        => 1,
	'paginationSpacing'           => 20,
	'paginationAlignment'         => 'left',
	'paginationNextText'          => '« Previous',
	'paginationPrevText'          => 'Next »',
	'imgPosition'                 => 'top',

	'rowGapUnit'                  => 'px',
	'columnGapUnit'               => 'px',
	'contentPaddingUnit'          => 'px',
	'excerptBottomSpaceUnit'      => 'px',

	'displayPostContentRadio'     => 'excerpt',
	'paginationSpacingUnit'       => 'px',
	'imageBottomSpaceUnit'        => 'px',
	'titleBottomSpaceUnit'        => 'px',
	'metaBottomSpaceUnit'         => 'px',
	'ctaBottomSpaceUnit'          => 'px',
	'titleTransform'              => '',
	'metaTransform'               => '',
	'excerptTransform'            => '',
	'ctaTransform'                => '',
	'titleDecoration'             => '',
	'metaDecoration'              => '',
	'excerptDecoration'           => '',
	'ctaDecoration'               => '',
	'paddingBtnTopTablet'         => '',
	'paddingBtnRightTablet'       => '',
	'paddingBtnBottomTablet'      => '',
	'paddingBtnLeftTablet'        => '',
	'paddingBtnTopMobile'         => '',
	'paddingBtnRightMobile'       => '',
	'paddingBtnBottomMobile'      => '',
	'paddingBtnLeftMobile'        => '',
	'paddingBtnUnit'              => 'px',
	'mobilePaddingBtnUnit'        => 'px',
	'tabletPaddingBtnUnit'        => 'px',
	'spacingLink'                 => '',
	'spacingLinkPadding'          => '',
	'paddingTopTablet'            => '',
	'paddingRightTablet'          => '',
	'paddingBottomTablet'         => '',
	'paddingLeftTablet'           => '',
	'paddingUnit'                 => 'px',
	'mobilePaddingUnit'           => 'px',
	'tabletPaddingUnit'           => 'px',
	'layoutConfig'                => array(
		array( 'uagb/post-image' ),
		array( 'uagb/post-title' ),
		array( 'uagb/post-meta' ),
		array( 'uagb/post-excerpt' ),
		array( 'uagb/post-button' ),
	),
);
