<?php
/**
 * Attributes File.
 *
 * @since x.x.x
 *
 * @package uagb
 */

return array(
	'classMigrate'            => false,
	'block_id'                => '',
	'align'                   => 'center',
	'tag'                     => 'h3',
	'titleColor'              => '',
	'prefixColor'             => '#888888',
	'descColor'               => '',
	'socialColor'             => '#333',
	'socialHoverColor'        => '',
	'titleFontFamily'         => '',
	'titleLoadGoogleFonts'    => false,
	'titleFontWeight'         => '',
	'titleFontSubset'         => '',
	'titleFontSize'           => '',
	'titleFontSizeType'       => 'px',
	'titleFontSizeTablet'     => '',
	'titleFontSizeMobile'     => '',
	'titleLineHeight'         => '',
	'titleLineHeightType'     => 'em',
	'titleLineHeightTablet'   => '',
	'titleLineHeightMobile'   => '',
	'prefixFontFamily'        => '',
	'prefixLoadGoogleFonts'   => false,
	'prefixFontWeight'        => '',
	'prefixFontSubset'        => '',
	'prefixFontSize'          => 15,
	'prefixFontSizeType'      => 'px',
	'prefixFontSizeTablet'    => '',
	'prefixFontSizeMobile'    => '',
	'prefixLineHeight'        => '',
	'prefixLineHeightType'    => 'em',
	'prefixLineHeightTablet'  => '',
	'prefixLineHeightMobile'  => '',
	'descFontFamily'          => '',
	'descLoadGoogleFonts'     => false,
	'descFontWeight'          => '',
	'descFontSubset'          => '',
	'descFontSize'            => 15,
	'descFontSizeType'        => 'px',
	'descFontSizeTablet'      => '',
	'descFontSizeMobile'      => '',
	'descLineHeight'          => '',
	'descLineHeightType'      => 'em',
	'descLineHeightTablet'    => '',
	'descLineHeightMobile'    => '',
	'socialFontSize'          => 20,
	'socialFontSizeType'      => 'px',
	'socialFontSizeMobile'    => '',
	'socialFontSizeTablet'    => '',
	'image'                   => '',
	'imgStyle'                => 'normal',
	'imgPosition'             => 'above',
	'imgAlign'                => 'top',
	'imgSiz'                  => 'thumbnail',
	'imgWidth'                => 120,
	'titleSpace'              => '',
	'prefixSpace'             => '',
	'descSpace'               => 10,
	'imgLeftMargin'           => 'auto',
	'imgRightMargin'          => 'auto',
	'imgTopMargin'            => 15,
	'imgBottomMargin'         => 15,
	'imageMarginLeftTablet'   => 'auto',
	'imageMarginRightTablet'  => 'auto',
	'imageMarginTopTablet'    => '',
	'imageMarginBottomTablet' => '',
	'imageMarginLeftMobile'   => 'auto',
	'imageMarginRightMobile'  => 'auto',
	'imageMarginTopMobile'    => '',
	'imageMarginBottomMobile' => '',
	'imageMarginUnit'         => 'px',
	'tabletImageMarginUnit'   => 'px',
	'mobileImageMarginUnit'   => 'px',
	'spacingLink'             => false,
	'socialSpace'             => 20,
	'headingTag'              => 'h3',
);
