// Actions
export const ACTIONS = {
	SET_SCREENS: 'SET_SCREENS',
	SET_CURRENT_SCREEN: 'SET_CURRENT_SCREEN',
	UPDATE_STATE: 'UPDATE_STATE',
	SET_LOADING: 'SET_LOADING',
	SET_ERROR: 'SET_ERROR',
	SET_USER_INFO: 'SET_USER_INFO',
	SET_PRO_FEATURES: 'SET_PRO_FEATURES',
	SET_PRO_STATUS: 'SET_PRO_STATUS',
	SET_SELECTED_ADDONS: 'SET_SELECTED_ADDONS',
	SET_ACTIVATED_ADDONS: 'SET_ACTIVATED_ADDONS',
	SET_STARTER_TEMPLATES_BUILDER: 'SET_STARTER_TEMPLATES_BUILDER',
};
