<?php
/**
 * Block Information & Attributes File.
 *
 * @since x.x.x
 *
 * @package uagb
 */

$block_slug = 'uagb/content-timeline';
$block_data = array(
	'slug'        => '',
	'title'       => __( 'Content Timeline', 'ultimate-addons-for-gutenberg' ),
	'description' => __( 'The Timeline block lets you create beautiful timelines on your website.', 'ultimate-addons-for-gutenberg' ),
	'default'     => true,
	'extension'   => false,
	'js_assets'   => array( 'uagb-timeline-js' ),
	'attributes'  => array(
		'classMigrate'            => false,
		'align'                   => 'center',
		'headingColor'            => '',
		'subHeadingColor'         => '',
		'separatorBg'             => '#eee',
		'backgroundColor'         => '#eee',
		'separatorColor'          => '#eee',
		'separatorFillColor'      => '#61ce70',
		'separatorBorder'         => '#eee',
		'borderFocus'             => '#5cb85c',
		'horizontalSpace'         => 10,
		'verticalSpace'           => 15,
		'headFontSizeType'        => 'px',
		'headFontSize'            => '',
		'headFontSizeTablet'      => '',
		'headFontSizeMobile'      => '',
		'headFontFamily'          => '',
		'headFontWeight'          => '',
		'headFontSubset'          => '',
		'headLineHeightType'      => 'em',
		'headLineHeight'          => '',
		'headLineHeightTablet'    => '',
		'headLineHeightMobile'    => '',
		'headLoadGoogleFonts'     => false,
		'timelinAlignment'        => 'center',
		'arrowlinAlignment'       => 'center',
		'subHeadFontSizeType'     => 'px',
		'subHeadFontSize'         => '',
		'subHeadFontSizeTablet'   => '',
		'subHeadFontSizeMobile'   => '',
		'subHeadFontFamily'       => '',
		'subHeadFontWeight'       => '',
		'subHeadFontSubset'       => '',
		'subHeadLineHeightType'   => 'em',
		'subHeadLineHeight'       => '',
		'subHeadLineHeightTablet' => '',
		'subHeadLineHeightMobile' => '',
		'subHeadLoadGoogleFonts'  => false,
		'headSpace'               => 5,
		'separatorwidth'          => 3,
		'borderwidth'             => 0,
		'iconColor'               => '#333',
		'iconFocus'               => '#fff',
		'iconBgFocus'             => '#61ce70',
		'dateColor'               => '#333',
		'dateFontsizeType'        => 'px',
		'dateFontsize'            => '12',
		'dateFontsizeTablet'      => '',
		'dateFontsizeMobile'      => '',
		'dateFontFamily'          => '',
		'dateFontWeight'          => '',
		'dateFontSubset'          => '',
		'dateLineHeightType'      => 'em',
		'dateLineHeight'          => '',
		'dateLineHeightTablet'    => '',
		'dateLineHeightMobile'    => '',
		'dateLoadGoogleFonts'     => false,
		'connectorBgsize'         => 35,
		'dateBottomspace'         => 5,
		'borderRadius'            => 2,
		'bgPadding'               => 20,
		'iconSize'                => 12,
		'stack'                   => 'tablet',
		'topMarginTablet'         => '',
		'rightMarginTablet'       => '',
		'bottomMarginTablet'      => '',
		'leftMarginTablet'        => '',
		'topMarginMobile'         => '',
		'rightMarginMobile'       => '',
		'bottomMarginMobile'      => '',
		'leftMarginMobile'        => '',
		'marginUnit'              => 'px',
		'mobileMarginUnit'        => 'px',
		'tabletMarginUnit'        => 'px',
		'marginLink'              => false,
		'topPaddingTablet'        => '',
		'rightPaddingTablet'      => '',
		'bottomPaddingTablet'     => '',
		'leftPaddingTablet'       => '',
		'topPaddingMobile'        => '',
		'rightPaddingMobile'      => '',
		'bottomPaddingMobile'     => '',
		'leftPaddingMobile'       => '',
		'paddingUnit'             => 'px',
		'mobilePaddingUnit'       => 'px',
		'tabletPaddingUnit'       => 'px',
		'paddingLink'             => false,
	),
);
