<?php
/**
 * Attributes File.
 *
 * @since x.x.x
 *
 * @package uagb
 */

return array(
	'classMigrate'           => false,
	'block_id'               => '',
	'columns'                => '2',
	'align'                  => '',
	'vAlign'                 => '',
	'stack'                  => 'mobile',
	'topPadding'             => '20',
	'bottomPadding'          => '20',
	'leftPadding'            => '20',
	'rightPadding'           => '20',
	'topMargin'              => '0',
	'bottomMargin'           => '0',
	'topPaddingTablet'       => '',
	'bottomPaddingTablet'    => '',
	'leftPaddingTablet'      => '',
	'rightPaddingTablet'     => '',
	'topPaddingMobile'       => '',
	'bottomPaddingMobile'    => '',
	'leftPaddingMobile'      => '',
	'rightPaddingMobile'     => '',
	'topMarginMobile'        => '',
	'bottomMarginMobile'     => '',
	'topMarginTablet'        => '',
	'bottomMarginTablet'     => '',
	'contentWidth'           => 'theme',
	'width'                  => '900',
	'widthType'              => 'px',
	'tag'                    => 'section',
	'backgroundType'         => 'none',
	'backgroundImage'        => '',
	'backgroundPosition'     => 'center-center',
	'backgroundSize'         => 'cover',
	'backgroundRepeat'       => 'no-repeat',
	'backgroundAttachment'   => 'scroll',
	'backgroundVideo'        => '',
	'backgroundColor'        => '',
	'gradientColor1'         => '',
	'gradientColor2'         => '',
	'gradientType'           => 'linear',
	'gradientLocation1'      => '0',
	'gradientLocation2'      => '100',
	'gradientAngle'          => '0',
	'gradientPosition'       => 'center center',
	'backgroundOpacity'      => '',
	'backgroundVideoOpacity' => '50',
	'backgroundVideoColor'   => '',
	'backgroundImageColor'   => '',
	'borderStyle'            => 'none',
	'borderWidth'            => '1',
	'borderRadius'           => '',
	'borderColor'            => '',
	'borderHoverColor'       => '',
	'columnGap'              => '10',
	'bottomType'             => 'none',
	'bottomColor'            => '#333',
	'bottomHeight'           => '',
	'bottomHeightTablet'     => '',
	'bottomHeightMobile'     => '',
	'bottomWidth'            => '',
	'topType'                => 'none',
	'topColor'               => '#333',
	'topHeight'              => '',
	'topHeightTablet'        => '',
	'topHeightMobile'        => '',
	'topWidth'               => '',
	'bottomFlip'             => '',
	'topFlip'                => '',
	'mobileMarginType'       => 'px',
	'tabletMarginType'       => 'px',
	'desktopMarginType'      => 'px',
	'mobilePaddingType'      => 'px',
	'tabletPaddingType'      => 'px',
	'desktopPaddingType'     => 'px',
	'boxShadowColor'         => '',
	'boxShadowHOffset'       => 0,
	'boxShadowVOffset'       => 0,
	'boxShadowBlur'          => '',
	'boxShadowSpread'        => '',
	'boxShadowPosition'      => 'outset',
	'gradientValue'          => '',
);
