<?php
/**
 * Block Information & Attributes File.
 *
 * @since x.x.x
 *
 * @package uagb
 */

$block_slug = 'uagb/taxonomy-list';
$block_data = array(
	'slug'        => '',
	'title'       => __( 'Taxonomy List', 'ultimate-addons-for-gutenberg' ),
	'description' => __( 'This block helps you to display content categorization for various post types', 'ultimate-addons-for-gutenberg' ),
	'default'     => true,
	'attributes'  => array(
		'block_id'                 => '',
		'postType'                 => 'post',
		'taxonomyType'             => 'category',
		'titleTag'                 => '',
		'categories'               => '',
		'order'                    => 'desc',
		'orderBy'                  => 'date',
		'postsToShow'              => 8,
		'layout'                   => 'grid',
		'columns'                  => 3,
		'tcolumns'                 => 2,
		'mcolumns'                 => 1,
		'bgColor'                  => '#f5f5f5',
		'titleColor'               => '#3b3b3b',
		'countColor'               => '#777777',
		'listTextColor'            => '#3b3b3b',
		'hoverlistTextColor'       => '#3b3b3b',
		'listStyleColor'           => '#3b3b3b',
		'hoverlistStyleColor'      => '#3b3b3b',
		'rowGap'                   => 20,
		'columnGap'                => 20,
		'contentPadding'           => 20,
		'contentPaddingMobile'     => 15,
		'contentPaddingTablet'     => 15,
		'titleBottomSpace'         => 15,
		'listBottomMargin'         => 10,
		'alignment'                => 'center',
		'listStyle'                => 'disc',
		'seperatorStyle'           => 'none',
		'seperatorWidth'           => 100,
		'seperatorThickness'       => 1,
		'seperatorColor'           => '#b2b4b5',
		'seperatorHoverColor'      => '#b2b4b5',
		'boxShadowColor'           => '',
		'boxShadowHOffset'         => 0,
		'boxShadowVOffset'         => 0,
		'boxShadowBlur'            => '',
		'boxShadowSpread'          => '',
		'boxShadowPosition'        => 'outset',
		'titleFontSize'            => '',
		'titleFontSizeType'        => 'px',
		'titleFontSizeMobile'      => '',
		'titleFontSizeTablet'      => '',
		'titleFontFamily'          => '',
		'titleFontWeight'          => '',
		'titleFontSubset'          => '',
		'titleLineHeightType'      => 'em',
		'titleLineHeight'          => '',
		'titleLineHeightTablet'    => '',
		'titleLineHeightMobile'    => '',
		'titleLoadGoogleFonts'     => false,
		'countFontSize'            => '',
		'countFontSizeType'        => 'px',
		'countFontSizeMobile'      => '',
		'countFontSizeTablet'      => '',
		'countFontFamily'          => '',
		'countFontWeight'          => '',
		'countFontSubset'          => '',
		'countLineHeightType'      => 'em',
		'countLineHeight'          => '',
		'countLineHeightTablet'    => '',
		'countLineHeightMobile'    => '',
		'countLoadGoogleFonts'     => false,
		'listFontSize'             => '',
		'listFontSizeType'         => 'px',
		'listFontSizeMobile'       => '',
		'listFontSizeTablet'       => '',
		'listFontFamily'           => '',
		'listFontWeight'           => '',
		'listFontSubset'           => '',
		'listLineHeightType'       => 'em',
		'listLineHeight'           => '',
		'listLineHeightTablet'     => '',
		'listLineHeightMobile'     => '',
		'listLoadGoogleFonts'      => false,
		'borderStyle'              => 'solid',
		'borderThickness'          => 1,
		'borderRadius'             => 0,
		'borderColor'              => '#E0E0E0',
		'borderHoverColor'         => '#E0E0E0',
		'noTaxDisplaytext'         => __( 'Taxonomy Not Available.', 'ultimate-addons-for-gutenberg' ),
		'showCount'                => true,
		'showEmptyTaxonomy'        => false,
		'showhierarchy'            => false,
		'listDisplayStyle'         => 'list',
		'contentPaddingUnit'       => 'px',
		'mobileContentPaddingUnit' => 'px',
		'tabletContentPaddingUnit' => 'px',
		'contentPaddingLink'       => false,
	),
);
