<?php
/**
 * Block Information & Attributes File.
 *
 * @since 2.0.0
 *
 * @package uagb
 */

return array(
	'classMigrate'            => false,
	'headingAlign'            => 'center',
	'headingColor'            => '',
	'subHeadingColor'         => '',
	'separatorColor'          => '#0170b9',
	'seperatorStyle'          => 'none',
	'separatorHeight'         => 2,
	'separatorWidth'          => 12,
	'separatorWidthType'      => '%',
	'headFontFamily'          => '',
	'headLoadGoogleFonts'     => false,
	'headFontWeight'          => '',
	'headFontStyle'           => '',
	'headFontSize'            => '',
	'headFontSizeType'        => 'px',
	'headFontSizeTablet'      => '',
	'headFontSizeMobile'      => '',
	'headLineHeight'          => '',
	'headLineHeightType'      => 'em',
	'headLineHeightTablet'    => '',
	'headLineHeightMobile'    => '',
	'headLetterSpacing'			=> '',
	'headLetterSpacingTablet'	=> '',
	'headLetterSpacingMobile'	=> '',
	'headLetterSpacingType'		=> 'px',
	'subHeadFontFamily'       => '',
	'subHeadLoadGoogleFonts'  => false,
	'subHeadFontWeight'       => '',
	'subHeadFontStyle'        => '',
	'subHeadFontSize'         => '',
	'subHeadFontSizeType'     => 'px',
	'subHeadFontSizeTablet'   => '',
	'subHeadFontSizeMobile'   => '',
	'subHeadLineHeight'       => '',
	'subHeadLineHeightType'   => 'em',
	'subHeadLineHeightTablet' => '',
	'subHeadLineHeightMobile' => '',
	'subHeadLetterSpacing'			=> '',
	'subHeadLetterSpacingTablet'	=> '',
	'subHeadLetterSpacingMobile'	=> '',
	'subHeadLetterSpacingType'		=> 'px',
	'headSpace'               => 15,
	'separatorSpace'          => 15,
	'separatorHoverColor'     => '',
	'headTransform'           => '',
	'headDecoration'          => '',
	'subHeadTransform'        => '',
	'subHeadDecoration'       => '',
	// padding.
	'headingBlockTopPadding'              => '',
	'headingBlockRightPadding'            => '',
	'headingBlockLeftPadding'             => '',
	'headingBlockBottomPadding'           => '',
	'headingBlockTopPaddingTablet'        => '',
	'headingBlockRightPaddingTablet'      => '',
	'headingBlockLeftPaddingTablet'       => '',
	'headingBlockBottomPaddingTablet'     => '',
	'headingBlockTopPaddingMobile'        => '',
	'headingBlockRightPaddingMobile'      => '',
	'headingBlockLeftPaddingMobile'       => '',
	'headingBlockBottomPaddingMobile'     => '',
	'headingBlockPaddingUnit'             => 'px',
	'headingBlockPaddingUnitTablet'       => 'px',
	'headingBlockPaddingUnitMobile'       => 'px',
	'headingBlockPaddingLink'             => '',
	// margin.
	'headingBlockTopMargin'              => '',
	'headingBlockRightMargin'            => '',
	'headingBlockLeftMargin'             => '',
	'headingBlockBottomMargin'           => '',
	'headingBlockTopMarginTablet'        => '',
	'headingBlockRightMarginTablet'      => '',
	'headingBlockLeftMarginTablet'       => '',
	'headingBlockBottomMarginTablet'     => '',
	'headingBlockTopMarginMobile'        => '',
	'headingBlockRightMarginMobile'      => '',
	'headingBlockLeftMarginMobile'       => '',
	'headingBlockBottomMarginMobile'     => '',
	'headingBlockMarginUnit'             => 'px',
	'headingBlockMarginUnitTablet'       => 'px',
	'headingBlockMarginUnitMobile'       => 'px',
	'headingBlockMarginLink'             => '',
	// link
	'linkColor'            				=> '',
	'linkHColor'             			=> '',
);
