<?php
/**
 * Block Information & Attributes File.
 *
 * @since 2.0.0
 *
 * @package uagb
 */

return array(
	'classMigrate'                    => false,
	'headingAlign'                    => 'center',
	'headingColor'                    => '',
	'headingColorType'                => 'classic',
	'headingGradientColor'            => 'linear-gradient(90deg, rgb(6, 147, 227) 0%, rgb(155, 81, 224) 100%)',
	'headingBackground'               => '',
	'headingBackgroundType'           => 'classic',
	'headingGradientBackground'       => 'linear-gradient(90deg, rgb(6, 147, 227) 0%, rgb(155, 81, 224) 100%)',
	'subHeadingColor'                 => '',
	'separatorColor'                  => '#0170b9',
	'seperatorStyle'                  => 'none',
	'separatorHeight'                 => 2,
	'separatorWidth'                  => 12,
	'separatorWidthTablet'            => '',
	'separatorWidthMobile'            => '',
	'separatorWidthType'              => '%',
	'headFontFamily'                  => '',
	'headLoadGoogleFonts'             => false,
	'headFontWeight'                  => '',
	'headFontStyle'                   => '',
	'headFontSize'                    => '',
	'headFontSizeType'                => 'px',
	'headFontSizeTablet'              => '',
	'headFontSizeMobile'              => '',
	'headLineHeight'                  => '',
	'headLineHeightType'              => 'em',
	'headLineHeightTablet'            => '',
	'headLineHeightMobile'            => '',
	'headLetterSpacing'               => '',
	'headLetterSpacingTablet'         => '',
	'headLetterSpacingMobile'         => '',
	'headLetterSpacingType'           => 'px',
	'headShadowColor'                 => '',
	'headShadowHOffset'               => '',
	'headShadowVOffset'               => '',
	'headShadowBlur'                  => '',
	'subHeadFontFamily'               => '',
	'subHeadLoadGoogleFonts'          => false,
	'subHeadFontWeight'               => '',
	'subHeadFontStyle'                => '',
	'subHeadFontSize'                 => '',
	'subHeadFontSizeType'             => 'px',
	'subHeadFontSizeTablet'           => '',
	'subHeadFontSizeMobile'           => '',
	'subHeadLineHeight'               => '',
	'subHeadLineHeightType'           => 'em',
	'subHeadLineHeightTablet'         => '',
	'subHeadLineHeightMobile'         => '',
	'subHeadLetterSpacing'            => '',
	'subHeadLetterSpacingTablet'      => '',
	'subHeadLetterSpacingMobile'      => '',
	'subHeadLetterSpacingType'        => 'px',
	'headSpace'                       => 15,
	'headSpaceTablet'                 => '',
	'headSpaceMobile'                 => '',
	'separatorSpace'                  => 15,
	'separatorSpaceTablet'            => '',
	'separatorSpaceMobile'            => '',
	'separatorHoverColor'             => '',
	'headTransform'                   => '',
	'headDecoration'                  => '',
	'subHeadTransform'                => '',
	'subHeadDecoration'               => '',
	// padding.
	'headingBlockTopPadding'          => '',
	'headingBlockRightPadding'        => '',
	'headingBlockLeftPadding'         => '',
	'headingBlockBottomPadding'       => '',
	'headingBlockTopPaddingTablet'    => '',
	'headingBlockRightPaddingTablet'  => '',
	'headingBlockLeftPaddingTablet'   => '',
	'headingBlockBottomPaddingTablet' => '',
	'headingBlockTopPaddingMobile'    => '',
	'headingBlockRightPaddingMobile'  => '',
	'headingBlockLeftPaddingMobile'   => '',
	'headingBlockBottomPaddingMobile' => '',
	'headingBlockPaddingUnit'         => 'px',
	'headingBlockPaddingUnitTablet'   => 'px',
	'headingBlockPaddingUnitMobile'   => 'px',
	'headingBlockPaddingLink'         => '',
	// margin.
	'headingBlockTopMargin'           => '',
	'headingBlockRightMargin'         => '',
	'headingBlockLeftMargin'          => '',
	'headingBlockBottomMargin'        => '',
	'headingBlockTopMarginTablet'     => '',
	'headingBlockRightMarginTablet'   => '',
	'headingBlockLeftMarginTablet'    => '',
	'headingBlockBottomMarginTablet'  => '',
	'headingBlockTopMarginMobile'     => '',
	'headingBlockRightMarginMobile'   => '',
	'headingBlockLeftMarginMobile'    => '',
	'headingBlockBottomMarginMobile'  => '',
	'headingBlockMarginUnit'          => 'px',
	'headingBlockMarginUnitTablet'    => 'px',
	'headingBlockMarginUnitMobile'    => 'px',
	'headingBlockMarginLink'          => '',
	// link.
	'linkColor'                       => '',
	'linkHColor'                      => '',
	// Highlight.
	'highLightColor'                  => '#f78a0c',
	'highLightBackground'             => '',
	'highLightBorderWidth'            => '',
	'highLightBorderRadius'           => '',
	'highLightBorderStyle'            => 'none',
	'highLightBorderColor'            => '',
	'highLightBorderHColor'           => '',
	'highLightLoadGoogleFonts'        => false,
	'highLightFontFamily'             => 'Default',
	'highLightFontWeight'             => '',
	'highLightFontStyle'              => 'normal',
	'highLightTransform'              => '',
	'highLightDecoration'             => '',
	'highLightFontSizeType'           => 'px',
	'highLightLineHeightType'         => 'em',
	'highLightFontSize'               => '',
	'highLightFontSizeTablet'         => '',
	'highLightFontSizeMobile'         => '',
	'highLightLineHeight'             => '',
	'highLightLineHeightTablet'       => '',
	'highLightLineHeightMobile'       => '',
	'highLightLetterSpacing'          => '',
	'highLightLetterSpacingTablet'    => '',
	'highLightLetterSpacingMobile'    => '',
	'highLightLetterSpacingType'      => 'px',
	'highLightTopPadding'             => '',
	'highLightRightPadding'           => '',
	'highLightLeftPadding'            => '',
	'highLightBottomPadding'          => '',
	'highLightTopPaddingTablet'       => '',
	'highLightRightPaddingTablet'     => '',
	'highLightLeftPaddingTablet'      => '',
	'highLightBottomPaddingTablet'    => '',
	'highLightTopPaddingMobile'       => '',
	'highLightRightPaddingMobile'     => '',
	'highLightLeftPaddingMobile'      => '',
	'highLightBottomPaddingMobile'    => '',
	'highLightPaddingUnit'            => 'px',
	'highLightPaddingUnitTablet'      => 'px',
	'highLightPaddingUnitMobile'      => 'px',
	'highLightPaddingLink'            => '',
);
