<?php
/**
 * Attributes File.
 *
 * @since 2.0.0
 *
 * @package uagb
 */

return array(
	'classMigrate'       => false,
	'childMigrate'       => false,
	'align'              => 'left',
	'icon_count'         => '1',
	'icons'              => array(
		array(
			'label'                   => __( 'Label #1', 'ultimate-addons-for-gutenberg' ),
			'image_icon'              => 'icon',
			'icon'                    => 'fab fa-facebook',
			'image'                   => '',
			'icon_color'              => '',
			'icon_hover_color'        => '',
			'icon_bg_color'           => '',
			'icon_bg_hover_color'     => '',
			'icon_border_color'       => '',
			'icon_border_hover_color' => '',
			'label_color'             => '',
			'label_hover_color'       => '',
			'link'                    => '#',
			'target'                  => false,
		),
	),
	'gap'                => '10',
	'gapTablet'          => '10',
	'gapMobile'          => '10',
	'gapType'            => 'px',
	'inner_gap'          => '15',
	'innerGapTablet'     => '',
	'innerGapMobile'     => '',
	'innerGapType'       => 'px',
	'size'               => '16',
	'sizeType'           => 'px',
	'sizeMobile'         => '',
	'sizeTablet'         => '',
	'bgSize'             => '0',
	'bgSizeType'         => 'px',
	'border'             => '0',
	'borderTablet'       => '0',
	'borderMobile'       => '0',
	'borderType'         => 'px',
	'borderRadius'       => '0',
	'borderRadiusTablet' => '0',
	'borderRadiusMobile' => '0',
	'borderRadiusType'   => 'px',
	'fontSize'           => '',
	'fontSizeType'       => 'px',
	'fontSizeMobile'     => '',
	'fontSizeTablet'     => '',
	'lineHeight'         => '',
	'lineHeightType'     => 'em',
	'lineHeightMobile'   => '',
	'lineHeightTablet'   => '',
	'fontFamily'         => '',
	'fontWeight'         => '',
	'loadGoogleFonts'    => false,
	'icon_layout'        => 'vertical',
	'stack'              => 'none',
	'fontStyle'          => '',
	'fontTransform'      => '',
	'fontDecoration'     => '',
	'hideLabel'          => true,
	'iconPosition'       => 'middle',
);
