name: PHPUnit Tests

on:
  workflow_dispatch:

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer
          ini-values: error_reporting=E_ALL

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run Spectra V3 PHPUnit Tests
        run: |
          echo "=== Running Spectra V3 PHPUnit Tests ==="
          echo "PHP Version: $(php -v | head -n1)"
          echo "PHPUnit Version: $(vendor/bin/phpunit --version)"
          echo "Working Directory: $(pwd)"
          echo "Test Configuration: phpunit.xml.dist"
          echo ""
          
          # Run the Spectra V3 test suite directly
          composer run test:spectra-v3
          
          echo ""
          echo "=== Test execution completed ==="

      - name: Display test results summary
        if: always()
        run: |
          echo "=== Test Results Summary ==="
          echo "PHP Version: ${{ matrix.php }}"
          echo "Status: ${{ job.status }}"
          echo "Runner: ${{ runner.os }}"
